onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - supabase

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
  tar@<7.5.7: ">=7.5.7"
  tar@<=7.5.2: ">=7.5.3"
  tar@<=7.5.3: ">=7.5.4"
  tmp@<=0.2.3: ">=0.2.4"
