onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - puppeteer

overrides:
  '@repere/core': link:../../AppData/Local/pnpm/global/5/node_modules/@repere/core
  '@repere/react': link:../../AppData/Local/pnpm/global/5/node_modules/@repere/react
