#!/bin/bash

# Soothsayer Local Development Setup Script
# This script helps you quickly set up local Supabase for development

set -e

echo "🚀 Soothsayer Local Development Setup"
echo "======================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running. Please start Docker Desktop first.${NC}"
    exit 1
fi

echo -e "${GREEN}[OK]${NC} Docker is running"

# Check if local network exists
if ! docker network inspect local-network > /dev/null 2>&1; then
    echo "[*] Creating Docker network..."
    docker network create -o "com.docker.network.bridge.host_binding_ipv4=127.0.0.1" local-network
    echo -e "${GREEN}[OK]${NC} Docker network created"
else
    echo -e "${GREEN}[OK]${NC} Docker network exists"
fi

# Check if volumes already exist (indicates existing data)
EXISTING_VOLUMES=$(docker volume ls -q | grep -c "supabase_db_soothsayer" || true)
if [ "$EXISTING_VOLUMES" -gt 0 ]; then
    echo -e "${GREEN}[INFO]${NC} Existing Supabase volumes found - your data will be preserved"
fi

# Start Supabase (preserves data via Docker volumes)
echo "[*] Starting Supabase (this may take a minute)..."
if ! pnpx supabase start --network-id local-network; then
    echo ""
    echo -e "${YELLOW}[!]${NC} Failed to start - likely container conflicts"
    echo "[*] Cleaning up containers and retrying (volumes preserved)..."

    # Stop Supabase cleanly (does NOT remove volumes by default)
    pnpx supabase stop > /dev/null 2>&1 || true

    # Force remove any stuck containers
    CONTAINERS=$(docker ps -aq --filter "name=supabase_")
    if [ -n "$CONTAINERS" ]; then
        echo "$CONTAINERS" | while read container; do
            docker rm -f "$container" > /dev/null 2>&1 || true
        done
    fi

    sleep 2

    # Retry start
    if ! pnpx supabase start --network-id local-network; then
        echo ""
        echo -e "${RED}[ERROR]${NC} Still failed to start Supabase"
        echo "Try: pnpm supabase:start:fresh"
        exit 1
    fi
fi

echo ""
echo -e "${GREEN}[OK]${NC} Supabase started successfully!"
echo ""

# Create .env.local if it doesn't exist
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}[!]${NC} .env.local already exists - skipping"
else
    echo "[*] Creating .env.local..."

    # Get publishable key from supabase status
    # The new table format has: │ Publishable │ sb_publishable_... │
    # We need to extract the second column (the actual key)
    PUBLISHABLE_KEY=$(pnpx supabase status | grep "Publishable" | awk -F'│' '{print $3}' | tr -d ' ')

    if [ -z "$PUBLISHABLE_KEY" ]; then
        echo -e "${YELLOW}[!]${NC} Could not auto-detect publishable key"
        echo "Please run 'pnpm supabase status' and copy the key manually to .env.local"
    else
        cat > .env.local << EOF
# Local Development Environment
# Auto-generated by setup-local-dev.sh

VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_ANON_KEY=$PUBLISHABLE_KEY
EOF
        echo -e "${GREEN}[OK]${NC} .env.local created"
    fi
fi

# Create supabase/functions/.env if it doesn't exist
if [ ! -f "supabase/functions/.env" ]; then
    echo ""
    echo "[*] Creating supabase/functions/.env..."

    # Generate a random cron secret
    GENERATED_CRON_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 64 | head -n 1)

    cat > supabase/functions/.env << 'EOF'
# Custom env vars that don't conflict with auto-injected SUPABASE_* vars
MY_SUPABASE_URL=http://kong:8000
MY_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
MY_SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
EOF
    echo "INTERNAL_CRON_SECRET=$GENERATED_CRON_SECRET" >> supabase/functions/.env

    echo -e "${GREEN}[OK]${NC} supabase/functions/.env created with generated INTERNAL_CRON_SECRET"
fi

# Always restart Edge Runtime if it's running (to ensure .env is loaded)
# Then restart Kong to clear its DNS cache — the Edge Runtime may get a new
# IP after restart and Kong would keep trying the stale one, causing timeouts.
if docker ps | grep -q "supabase_edge_runtime_soothsayer"; then
    echo "[*] Restarting Edge Runtime to ensure environment variables are loaded..."
    docker restart supabase_edge_runtime_soothsayer > /dev/null 2>&1
    echo "[*] Restarting Kong to refresh DNS cache..."
    docker restart supabase_kong_soothsayer > /dev/null 2>&1
    echo "[*] Waiting for services to be ready..."
    sleep 5
fi

# Populate local_config table with values from supabase/functions/.env
echo ""
echo "[*] Configuring local_config for cron jobs..."

# Read secrets from Edge Functions .env file
SERVICE_ROLE_KEY=$(grep "^MY_SUPABASE_SERVICE_ROLE_KEY=" supabase/functions/.env | cut -d'=' -f2)
CRON_SECRET=$(grep "^INTERNAL_CRON_SECRET=" supabase/functions/.env | cut -d'=' -f2)

if [ -n "$SERVICE_ROLE_KEY" ] && [ -n "$CRON_SECRET" ]; then
    # Insert config values into local_config table
    docker exec supabase_db_soothsayer psql -U postgres -c "
        INSERT INTO local_config (key, value) VALUES
            ('supabase_url', 'http://host.docker.internal:54321'),
            ('cron_secret', '$CRON_SECRET'),
            ('service_role_key', '$SERVICE_ROLE_KEY')
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
    " > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}[OK]${NC} local_config populated from supabase/functions/.env"
    else
        echo -e "${YELLOW}[!]${NC} Could not populate local_config (table may not exist yet)"
    fi
else
    if [ -z "$CRON_SECRET" ]; then
        echo -e "${YELLOW}[!]${NC} Missing INTERNAL_CRON_SECRET in supabase/functions/.env"
    fi
    if [ -z "$SERVICE_ROLE_KEY" ]; then
        echo -e "${YELLOW}[!]${NC} Could not detect service role key"
    fi
    echo -e "${YELLOW}[!]${NC} Cron jobs will not work until local_config is populated"
fi

# Check and report existing data
echo ""
echo "[*] Checking existing data..."
SNAPSHOT_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM snapshots;" 2>/dev/null | tr -d ' ' || echo "0")
CARD_PRICE_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM card_prices;" 2>/dev/null | tr -d ' ' || echo "0")
LEAGUE_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM poe_leagues;" 2>/dev/null | tr -d ' ' || echo "0")

if [ "$SNAPSHOT_COUNT" != "0" ] || [ "$CARD_PRICE_COUNT" != "0" ]; then
    echo -e "${GREEN}[OK]${NC} Found existing data:"
    echo "     - Leagues: $LEAGUE_COUNT"
    echo "     - Snapshots: $SNAPSHOT_COUNT"
    echo "     - Card prices: $CARD_PRICE_COUNT"
else
    echo -e "${YELLOW}[INFO]${NC} No snapshot data found (fresh database)"
    echo ""
    echo "[*] Populating initial data from PoE/poe.ninja..."
    echo "[*] Waiting for Edge Runtime to be fully ready..."
    sleep 5

    echo "[*] Syncing leagues from API..."
    docker exec supabase_db_soothsayer psql -U postgres -c "SELECT sync_leagues_from_api();" > /dev/null 2>&1

    # Wait for pg_net to process the request
    sleep 3

    echo "[*] Creating snapshots for active leagues (this may take a minute)..."
    docker exec supabase_db_soothsayer psql -U postgres -c "SELECT create_snapshots_for_active_leagues();" > /dev/null 2>&1

    # Wait for pg_net to process the requests
    sleep 10

    # Re-check data counts
    SNAPSHOT_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM snapshots;" 2>/dev/null | tr -d ' ' || echo "0")
    CARD_PRICE_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM card_prices;" 2>/dev/null | tr -d ' ' || echo "0")
    LEAGUE_COUNT=$(docker exec supabase_db_soothsayer psql -U postgres -t -c "SELECT COUNT(*) FROM poe_leagues;" 2>/dev/null | tr -d ' ' || echo "0")

    if [ "$SNAPSHOT_COUNT" != "0" ] && [ "$CARD_PRICE_COUNT" != "0" ]; then
        echo -e "${GREEN}[OK]${NC} Data populated:"
        echo "     - Leagues: $LEAGUE_COUNT"
        echo "     - Snapshots: $SNAPSHOT_COUNT"
        echo "     - Card prices: $CARD_PRICE_COUNT"
    else
        echo -e "${YELLOW}[!]${NC} Data population may still be in progress"
        echo "     Run 'pnpm supabase:sync' to check/retry"
    fi
fi

# Helper function to create clickable links (OSC 8 hyperlinks)
hyperlink() {
    local url="$1"
    local text="${2:-$url}"
    printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "$url" "$text"
}

echo ""
echo "======================================"
echo -e "${GREEN}>> Setup Complete!${NC}"
echo "======================================"
echo ""
echo "[DB] SQLite Database:"
echo "     - soothsayer.local.db  → local Supabase (localhost)"
echo "     - soothsayer.db        → dev with production credentials"
echo "     - soothsayer.prod.db   → installed release build"
echo "     - Automatic switching based on Supabase URL + app.isPackaged"
echo ""

echo "Next steps:"
echo ""
echo "1. Start the app:"
echo "   pnpm start"
echo ""
echo "2. Open Supabase Studio:"
echo -n "   🌐 "
hyperlink "http://127.0.0.1:54323" "http://127.0.0.1:54323"
echo ""
echo "3. API Endpoint:"
echo -n "   🔗 "
hyperlink "http://127.0.0.1:54321" "http://127.0.0.1:54321"
echo ""
echo "[INFO] Data is stored in Docker volumes and persists between restarts"
echo ""
echo "[TIP] Useful commands:"
echo "      pnpm supabase:sync        - Fetch fresh data from PoE/poe.ninja"
echo "      pnpm supabase:stop        - Stop containers (keeps data)"
echo "      pnpm supabase:start:fresh - Complete reset (deletes all data)"
echo ""
