#!/bin/bash

# Soothsayer Local Development Setup Script
# This script helps you quickly set up local Supabase for development

set -e

echo "🚀 Soothsayer Local Development Setup"
echo "======================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running. Please start Docker Desktop first.${NC}"
    exit 1
fi

echo -e "${GREEN}[OK]${NC} Docker is running"

# Check if local network exists
if ! docker network inspect local-network > /dev/null 2>&1; then
    echo "[*] Creating Docker network..."
    docker network create -o "com.docker.network.bridge.host_binding_ipv4=127.0.0.1" local-network
    echo -e "${GREEN}[OK]${NC} Docker network created"
else
    echo -e "${GREEN}[OK]${NC} Docker network exists"
fi

# Start Supabase (preserves data via Docker volumes)
echo "[*] Starting Supabase (this may take a minute)..."
if ! pnpx supabase start --network-id local-network; then
    echo ""
    echo -e "${YELLOW}[!]${NC} Failed to start - likely container conflicts"
    echo "[*] Cleaning up containers and retrying..."

    # Stop and remove containers (data persists in volumes)
    pnpx supabase stop > /dev/null 2>&1 || true

    CONTAINERS=$(docker ps -aq --filter "name=supabase_")
    if [ -n "$CONTAINERS" ]; then
        echo "$CONTAINERS" | while read container; do
            docker rm -f "$container" > /dev/null 2>&1 || true
        done
    fi

    sleep 2

    # Retry start
    if ! pnpx supabase start --network-id local-network; then
        echo ""
        echo -e "${RED}[ERROR]${NC} Still failed to start Supabase"
        echo "Try: pnpm supabase:start:fresh"
        exit 1
    fi
fi

echo ""
echo -e "${GREEN}[OK]${NC} Supabase started successfully!"
echo ""

# Create .env.local if it doesn't exist
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}[!]${NC} .env.local already exists - skipping"
else
    echo "[*] Creating .env.local..."

    # Get publishable key from supabase status
    # The new table format has: │ Publishable │ sb_publishable_... │
    # We need to extract the second column (the actual key)
    PUBLISHABLE_KEY=$(pnpx supabase status | grep "Publishable" | awk -F'│' '{print $3}' | tr -d ' ')

    if [ -z "$PUBLISHABLE_KEY" ]; then
        echo -e "${YELLOW}[!]${NC} Could not auto-detect publishable key"
        echo "Please run 'pnpm supabase status' and copy the key manually to .env.local"
    else
        cat > .env.local << EOF
# Local Development Environment
# Auto-generated by setup-local-dev.sh

VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_ANON_KEY=$PUBLISHABLE_KEY
EOF
        echo -e "${GREEN}[OK]${NC} .env.local created"
    fi
fi

# Auto-configure snapshot settings
echo ""
echo "[*] Configuring snapshot settings..."

# Get secret key from supabase status
# The new table format has: │ Secret │ sb_secret_... │
# We need to extract the second column (the actual key)
SECRET_KEY=$(pnpx supabase status | grep "Secret" | awk -F'│' '{print $3}' | tr -d ' ')

if [ -n "$SECRET_KEY" ]; then
    # Get cron secret from Edge Functions .env file
    CRON_SECRET=""
    if [ -f "supabase/functions/.env" ]; then
        CRON_SECRET=$(grep "^INTERNAL_CRON_SECRET=" supabase/functions/.env | cut -d'=' -f2)
    fi

    # Run the INSERT query with kong:8000 for Docker network and cron secret
    docker exec supabase_db_soothsayer psql -U postgres -c "INSERT INTO snapshot_settings (id, supabase_url, service_role_key, cron_secret, updated_at) VALUES (1, 'http://kong:8000', '$SECRET_KEY', '$CRON_SECRET', NOW()) ON CONFLICT (id) DO UPDATE SET supabase_url = EXCLUDED.supabase_url, service_role_key = EXCLUDED.service_role_key, cron_secret = EXCLUDED.cron_secret, updated_at = NOW();" > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}[OK]${NC} Snapshot settings configured automatically!"
    else
        echo -e "${YELLOW}[!]${NC} Could not auto-configure. You can do it manually in Studio."
    fi
else
    echo -e "${YELLOW}[!]${NC} Could not detect secret key. Configure manually if needed."
fi

# Helper function to create clickable links (OSC 8 hyperlinks)
hyperlink() {
    local url="$1"
    local text="${2:-$url}"
    printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "$url" "$text"
}

echo ""
echo "======================================"
echo -e "${GREEN}>> Setup Complete!${NC}"
echo "======================================"
echo ""
echo "[DB] SQLite Database:"
echo "     - Production: soothsayer.db (untouched)"
echo "     - Local Dev:  soothsayer.local.db (auto-created)"
echo "     - Automatic switching based on Supabase URL"
echo ""
echo "[OK] Snapshot settings: Configured automatically"
echo ""
echo "Next steps:"
echo ""
echo "1. Start the app:"
echo "   pnpm start"
echo ""
echo "2. Open Supabase Studio:"
echo -n "   🌐 "
hyperlink "http://127.0.0.1:54323" "http://127.0.0.1:54323"
echo ""
echo "3. API Endpoint:"
echo -n "   🔗 "
hyperlink "http://127.0.0.1:54321" "http://127.0.0.1:54321"
echo ""
echo "[TIP] Data persists in Docker volumes (survives container removal)"
echo "[TIP] Use 'pnpm supabase:stop' when done"
echo "[TIP] Use 'pnpm supabase:start:fresh' for clean slate"
echo ""
